version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - tpluscode
  assignees:
  - tpluscode
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/plugin-proposal-decorators"
    versions:
    - 7.12.12
    - 7.12.13
    - 7.13.5
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.12.7
  - dependency-name: standard-version
    versions:
    - 9.1.0
    - 9.1.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
